# RT-Thread building script for component
Import('RTT_ROOT')

from building import *

cwd = GetCurrentDir()
group = []
if GetDepend('NU_PKG_USING_RV3032C7'):
	src = Glob('*.c') + Glob('*.cpp')
	CPPPATH = [cwd]
	group = DefineGroup('nu_pkgs_rv3032c7', src, depend = [''], CPPPATH = CPPPATH)

Return('group')
