# RT-Thread building script for storage package bridge

import os
from building import *

cwd = GetCurrentDir()
objs = []
dir_list = os.listdir(cwd)

for d in dir_list:
    path = os.path.join(cwd, d)
    if os.path.isfile(os.path.join(path, 'SConscript')):
        objs = objs + SConscript(os.path.join(d, 'SConscript'))

Return('objs')