Import('RTT_ROOT')
from building import *

cwd = GetCurrentDir()
src = ['nu_miscutil.c']
CPPPATH = [cwd]
group = DefineGroup('numicro_common', src, depend = ['NU_PKG_USING_NUUTILS'], CPPPATH = CPPPATH)

Return('group')
